[doc]
name = 'resume'
bundle = 'https://data1.fullyjustified.net/tlextras-2022.0r0.tar'

[[output]]
name = 'default'
type = 'pdf'
preamble = "_preamble.tex"
index = "index.tex"
postamble = "_postamble.tex"
