name: Build PDF and archive

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-pdf:
    name: Build PDF and archive
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Set up mise-en-place
        uses: jdx/mise-action@v3
        with:
          cache: true
          install: true
      - name: Build the PDF
        run: mise run pdf
      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf
          if-no-files-found: error
